// <auto-generated />
using System;
using Flagbit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flagbit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlagbitDbContext))]
    partial class FlagbitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flagbit.Infrastructure.Persistence.Entities.FeatureFlagDependencyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DependencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dependency_key");

                    b.Property<long>("FeatureFlagId")
                        .HasColumnType("bigint")
                        .HasColumnName("feature_flag_id");

                    b.Property<string>("NormalizedDependencyKey")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalized_dependency_key")
                        .HasComputedColumnSql("upper(\"dependency_key\")", true);

                    b.HasKey("Id")
                        .HasName("pk_feature_flag_dependencies");

                    b.HasIndex("FeatureFlagId", "NormalizedDependencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_feature_flag_dependencies_flag_key");

                    b.ToTable("feature_flag_dependencies", (string)null);
                });

            modelBuilder.Entity("Flagbit.Infrastructure.Persistence.Entities.FeatureFlagEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("NormalizedKey")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalized_key")
                        .HasComputedColumnSql("upper(\"key\")", true);

                    b.Property<int?>("RolloutPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("rollout_percentage");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id")
                        .HasName("pk_feature_flags");

                    b.HasIndex("NormalizedKey")
                        .IsUnique()
                        .HasDatabaseName("ux_feature_flags_normalized_key");

                    b.ToTable("feature_flags", null, t =>
                        {
                            t.HasCheckConstraint("ck_feature_flags_rollout_percentage", "rollout_percentage IS NULL OR rollout_percentage BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_feature_flags_schedule", "starts_at IS NULL OR ends_at IS NULL OR starts_at <= ends_at");
                        });
                });

            modelBuilder.Entity("Flagbit.Infrastructure.Persistence.Entities.FeatureFlagEnvironmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FeatureFlagId")
                        .HasColumnType("bigint")
                        .HasColumnName("feature_flag_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name")
                        .HasComputedColumnSql("upper(\"name\")", true);

                    b.HasKey("Id")
                        .HasName("pk_feature_flag_environments");

                    b.HasIndex("FeatureFlagId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_feature_flag_environments_flag_name");

                    b.ToTable("feature_flag_environments", (string)null);
                });

            modelBuilder.Entity("Flagbit.Infrastructure.Persistence.Entities.FeatureFlagRuleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attribute");

                    b.Property<long>("FeatureFlagId")
                        .HasColumnType("bigint")
                        .HasColumnName("feature_flag_id");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_feature_flag_rules");

                    b.HasIndex("FeatureFlagId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_feature_flag_rules_flag_position");

                    b.ToTable("feature_flag_rules", null, t =>
                        {
                            t.HasCheckConstraint("ck_feature_flag_rules_position", "position >= 0");
                        });
                });

            modelBuilder.Entity("Flagbit.Infrastructure.Persistence.Entities.FeatureFlagTargetUserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FeatureFlagId")
                        .HasColumnType("bigint")
                        .HasColumnName("feature_flag_id");

                    b.Property<string>("NormalizedUserId")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_id")
                        .HasComputedColumnSql("upper(\"user_id\")", true);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_feature_flag_target_users");

                    b.HasIndex("FeatureFlagId", "NormalizedUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_feature_flag_target_users_flag_user");

                    b.ToTable("feature_flag_target_users", (string)null);
                });

            modelBuilder.Entity("Flagbit.Infrastructure.Persistence.Entities.FeatureFlagDependencyEntity", b =>
                {
                    b.HasOne("Flagbit.Infrastructure.Persistence.Entities.FeatureFlagEntity", "FeatureFlag")
                        .WithMany("Dependencies")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");
                });

            modelBuilder.Entity("Flagbit.Infrastructure.Persistence.Entities.FeatureFlagEnvironmentEntity", b =>
                {
                    b.HasOne("Flagbit.Infrastructure.Persistence.Entities.FeatureFlagEntity", "FeatureFlag")
                        .WithMany("Environments")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");
                });

            modelBuilder.Entity("Flagbit.Infrastructure.Persistence.Entities.FeatureFlagRuleEntity", b =>
                {
                    b.HasOne("Flagbit.Infrastructure.Persistence.Entities.FeatureFlagEntity", "FeatureFlag")
                        .WithMany("Rules")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");
                });

            modelBuilder.Entity("Flagbit.Infrastructure.Persistence.Entities.FeatureFlagTargetUserEntity", b =>
                {
                    b.HasOne("Flagbit.Infrastructure.Persistence.Entities.FeatureFlagEntity", "FeatureFlag")
                        .WithMany("TargetUsers")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");
                });

            modelBuilder.Entity("Flagbit.Infrastructure.Persistence.Entities.FeatureFlagEntity", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Environments");

                    b.Navigation("Rules");

                    b.Navigation("TargetUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
